import  = [
    "~/.config/alacritty/themes/themes/ashes_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"


[font]
normal.family = "Lilex Nerd Font Mono"

size = 16
